# Twitter Social Configs:
server:
  port : 9081

spring:
  social:
    twitter:
      appId: 
      appSecret: 
      accessToken: 
      accessTokenSecret: 

  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: tweets
